name: Validate PR Title

on:
  pull_request:

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        run: |
          echo "Validating PR Title: ${{ github.event.pull_request.title }}"

          PR_TITLE="${{ github.event.pull_request.title }}"

          # إزالة المسافات الزائدة
          PR_TITLE=$(echo "$PR_TITLE" | xargs)
          echo "Normalized PR Title: '$PR_TITLE'"

          # تعديل الـ regex ليتناسب مع الشكل المطلوب
          TITLE_REGEX='^(fix|release|feat|hotfix|build|test|feature)\/[A-Z]+-\d+-[A-Za-z0-9 ]+$'

          if ! [[ "$PR_TITLE" =~ $TITLE_REGEX ]]; then
            echo "❌ PR title does not match the expected format: 'type/TicketNum-TaskName'"
            echo "Allowed types: fix, release, feat, hotfix, build, test, feature"
            exit 1
          fi

          echo "✅ PR title is valid."
