name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title
        run: |
          echo "Validating PR Title: ${{ github.event.pull_request.title }}"

          PR_TITLE="${{ github.event.pull_request.title }}"

          # Define regex to validate PR title format
          TITLE_REGEX='^(fix|release|feat|hotfix|build|test)\/([A-Za-z0-9-]+)-\d+[- ]+[A-Za-z0-9 ]+$'

          # Validate PR title using regex
          if ! [[ "$PR_TITLE" =~ $TITLE_REGEX ]]; then
            echo "❌ PR title does not match the expected format: 'type/scope: TicketNum-task name'"
            echo "Allowed types: fix, release, feat, hotfix, build, test"
            echo "Allowed scopes: {project-ID-ticket num}, JIRA-\d+, [A-Z]+-\d+"
            exit 1
          fi

          echo "✅ PR title is valid."
